editor "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" -n -w
window_margin_width 10

font_size 14.0
disable_ligatures always

scrollback_lines 20000


strip_trailing_spaces always

initial_window_width 155c
initial_window_height 50c
single_window_margin_width 3
remember_window_size no

map cmd+enter new_window_with_cwd
map cmd+shift+enter new_os_window_with_cwd

copy_on_select clipboard

background_opacity 0.96
dynamic_background_opacity yes

macos_option_as_alt yes
macos_quit_when_last_window_closed yes

font_family JetBrainsMono Nerd Font

background #2f3566
foreground #d7e86a
cursor #d7e86a
selection_background #4a528f
selection_foreground #f8f8f2
color0  #20244a
color1  #ff6b6b
color2  #d7e86a
color3  #f0d95c
color4  #66d9ef
color5  #c792ea
color6  #66d9ef
color7  #e6e6e6
color8  #4a528f
color9  #ff8a8a
color10 #e6f58a
color11 #ffe36e
color12 #7fe7ff
color13 #d8a8ff
color14 #8be9fd
color15 #ffffff
active_border_color #ebce2d
inactive_border_color #ffffff
